# Generated by Django 4.1.3 on 2023-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_bottles', models.PositiveIntegerField()),
                ('rupees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
