# Generated by Django 4.1.3 on 2023-06-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
