# Generated by Django 4.1.3 on 2023-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=50)),
                ('number_of_bottles', models.IntegerField(max_length=50)),
                ('rupees', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
            ],
        ),
    ]
