# Generated by Django 4.1.3 on 2023-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='number_of_bottles',
            field=models.IntegerField(),
        ),
    ]
