# Generated by Django 4.1.3 on 2023-06-25 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_purchase_date_alter_purchase_rupees'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2023, 6, 25, 12, 49, 5, 402039)),
            preserve_default=False,
        ),
    ]
