# Generated by Django 4.1.3 on 2023-06-25 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2023, 6, 25, 12, 53, 31, 270362)),
            preserve_default=False,
        ),
    ]
