# Generated by Django 4.1.3 on 2023-06-25 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='rupees',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
