# Generated by Django 4.1.3 on 2023-06-25 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_purchase_date_alter_purchase_rupees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='rupees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
