# Generated by Django 4.1.3 on 2023-06-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_purchase_date_alter_purchase_rupees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
