# Generated by Django 4.1.3 on 2023-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_purchase_rupees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='rupees',
            field=models.IntegerField(),
        ),
    ]
